name: Build for Browser

on:
  workflow_dispatch:
    inputs:
      target_browser:
        description: Target browser
        type: choice
        required: true
        default: firefox
        options:
          - chrome
          - firefox
      is_development:
        description: Development build
        type: boolean
        required: true
        default: false
  workflow_call:
    inputs:
      target_browser:
        description: Target browser
        type: string
        required: true
      is_development:
        description: Development build
        type: boolean
        required: false
        default: false

jobs:
  build_variables:
    runs-on: ubuntu-latest
    name: Build variables
    outputs:
      is_development: ${{ steps.is_development.outputs.is_development }}
      artifact_name: ${{ steps.artifact_name.outputs.artifact_name }}
    steps:
      - name: Generate is development variable
        run: |
          is_development=false
          if [ "${{ inputs.is_development }}" == "true" ]; then
            is_development=true
          fi
          echo Is development: $is_development
          echo "is_development=$is_development" >> $GITHUB_OUTPUT

      - name: Generate artifact name
        id: artifact_name
        run: |
          artifact_name=$(echo artifact_${{ inputs.target_browser }})
          if [ "${{ inputs.is_development }}" == "true" ]; then
            artifact_name=$(echo ${artifact_name}_dev)
          fi
          echo Artifact name: $artifact_name
          echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT

  build:
    name: Build artifact
    runs-on: ubuntu-latest
    needs:
      - build_variables
    env:
      TARGET_BROWSER: ${{ inputs.target_browser }}
      IS_DEVELOPMENT: ${{ needs.build_variables.outputs.is_development }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew extension:packageExtension --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.build_variables.outputs.artifact_name }}
          path: |
            extension/build/distributions/*.zip
            extension/build/distributions/*.xpi
          if-no-files-found: error
